### ISSUE TITLE
add basic CI/CD pipeline

### ISSUE THREAD

**Issue by spmse** [JunusErgin/django-python-tutorial#1]
### Description

As a Developer, I want to write code and push my contributed changes to the remote repository. After a push to the repository I would expect a CI/CD pipeline to start execution and run through several steps, e.g. automatic container image creation, automatic vulnerability scans for container image, etc.

This will help to developers to focus on coding, while they will be notified/pinged in case something went wrong during the pipeline execution.

Ultimately this will prevent merges that would cause insecurities in the application and the general software quality would be increased.

## TODO

- [ ] add a basic github actions workflow for the project
- [ ] add two different jobs/steps within the pipeline that will:
    - [ ] create/build a docker image with the latest changes
    - [ ] scan the created image with [`trivy`](https://github.com/aquasecurity/trivy-action?tab=readme-ov-file#scan-ci-pipeline) or [`snyk`](https://github.com/snyk/actions) (both are open source projects)

## Acceptance Criteria

- The pipeline passes and successfully builds an image
- the pipeline scans the built image and reports issues that were found
